/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SkyVoiceImport } from './routes/sky-voice'
import { Route as SkyFaceImport } from './routes/sky-face'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SkyVoiceRoute = SkyVoiceImport.update({
  id: '/sky-voice',
  path: '/sky-voice',
  getParentRoute: () => rootRoute,
} as any)

const SkyFaceRoute = SkyFaceImport.update({
  id: '/sky-face',
  path: '/sky-face',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/sky-face': {
      id: '/sky-face'
      path: '/sky-face'
      fullPath: '/sky-face'
      preLoaderRoute: typeof SkyFaceImport
      parentRoute: typeof rootRoute
    }
    '/sky-voice': {
      id: '/sky-voice'
      path: '/sky-voice'
      fullPath: '/sky-voice'
      preLoaderRoute: typeof SkyVoiceImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sky-face': typeof SkyFaceRoute
  '/sky-voice': typeof SkyVoiceRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sky-face': typeof SkyFaceRoute
  '/sky-voice': typeof SkyVoiceRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/sky-face': typeof SkyFaceRoute
  '/sky-voice': typeof SkyVoiceRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sky-face' | '/sky-voice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sky-face' | '/sky-voice'
  id: '__root__' | '/' | '/sky-face' | '/sky-voice'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkyFaceRoute: typeof SkyFaceRoute
  SkyVoiceRoute: typeof SkyVoiceRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkyFaceRoute: SkyFaceRoute,
  SkyVoiceRoute: SkyVoiceRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/sky-face",
        "/sky-voice"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/sky-face": {
      "filePath": "sky-face.tsx"
    },
    "/sky-voice": {
      "filePath": "sky-voice.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
